version: '3.6'

services:
  activity-redis:
    container_name: user_activity_cache
    image: 'redis:alpine'
    networks:
      - user_activity
    hostname: redis
    ports:
      - '${USER_ACTIVITY_REDIS_PORT}:6379'

  activity-postgres:
    container_name: user_activity_persistence
    image: 'postgres:latest'
    ports:
      - '${USER_ACTIVITY_DB_PORT}:5432'
    volumes:
      - '${USER_ACTIVITY_DATA_PATH}:/data/postgres'
    environment:
      POSTGRES_USER: ${USER_ACTIVITY_DB_USER}
      POSTGRES_PASSWORD: ${USER_ACTIVITY_DB_PW}
      POSTGRES_DB: ${USER_ACTIVITY_DB_NAME}
    networks:
      - user_activity

  activity-pgadmin:
    links:
      - activity-postgres:postgres
    container_name: user_activity_pgadmin
    image: dpage/pgadmin4
    ports:
      - '${USER_ACTIVITY_DB_ADMIN_PORT}:80'
    volumes:
      - /data/pgadmin:/root/.pgadmin
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: admin
    networks:
      - user_activity
networks:
  user_activity:
