version: '3.6'

services:
  avatar-minio-server:
    container_name: user-avatar_minio-server
    image: minio/minio
    restart: always
    volumes:
      - ${USER_AVATAR_MINIO_DATA_ROOT_DIR}:/data
    networks:
      - user-avatar
    ports:
      - '${USER_AVATAR_MINIO_PORT}:9000'
      - '${USER_AVATAR_MINIO_CONSOLE_PORT}:9001'
    environment:
      MINIO_ACCESS_KEY: ${USER_AVATAR_MINIO_ACCESS_KEY}
      MINIO_SECRET_KEY: ${USER_AVATAR_MINIO_SECRET_KEY}
      MINIO_CACHE: "on"
      MINIO_CACHE_DRIVES: "/mnt/drive1,/mnt/drive2,/mnt/cache{1...3}"
      MINIO_CACHE_QUOTA: 80
      MINIO_CACHE_AFTER: 3
      MINIO_CACHE_WATERMARK_LOW: 70
      MINIO_CACHE_WATERMARK_HIGH: 90
    command: minio server --console-address :9001 /data

  avatar-minio-client:
    image: minio/mc
    container_name: user-avatar_client
    networks:
      - user-avatar
    # insure that the server container is running before building the client
    depends_on:
      - avatar-minio-server
    entrypoint: >
      /bin/sh -c "
      /usr/bin/mc config host add myminio http://avatar-minio-server:9000 ${USER_AVATAR_MINIO_ACCESS_KEY} ${USER_AVATAR_MINIO_SECRET_KEY};
      /usr/bin/mc mb myminio/avatar-bucket;
      echo 'my content' > testfile.txt;
      /usr/bin/mc cp myfile.txt myminio/avatar-bucket;
      exit 0;
      "
  avatar-redis:
    container_name: user-avatar_cache
    image: 'redis:alpine'
    networks:
      - user-avatar
    hostname: redis
    ports:
      - '${USER_AVATAR_REDIS_PORT}:6379'

  avatar-postgres:
    container_name: user-avatar_persistence
    image: 'postgres:latest'
    ports:
      - "${USER_AVATAR_DB_PORT}:5432"
    volumes:
      - '${USER_AVATAR_DATA_PATH}:/data/postgres'
    environment:
      POSTGRES_USER: ${USER_AVATAR_DB_USER}
      POSTGRES_PASSWORD: ${USER_AVATAR_DB_PW}
      POSTGRES_DB: ${USER_AVATAR_DB_NAME}
    networks:
      - user-avatar

  avatar-pgadmin:
    links:
      - avatar-postgres:postgres
    container_name: user_avatar_pgadmin
    image: dpage/pgadmin4
    ports:
      - "${USER_AVATAR_DB_ADMIN_PORT}:80"
    volumes:
      - /data/pgadmin:/root/.pgadmin
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: admin
    networks:
      - user-avatar
networks:
  user-avatar:
