version: '3.6'

services:
  messaging-minio-server:
    container_name: messsaging_minio-server
    image: minio/minio
    restart: always
    volumes:
      - ${MESSAGING_MINIO_DATA_ROOT_DIR}:/data
    networks:
      - messsaging
    ports:
      - '${MESSAGING_MINIO_PORT}:9000'
    environment:
      MINIO_ACCESS_KEY: ${MESSAGING_MINIO_ACCESS_KEY}
      MINIO_SECRET_KEY: ${MESSAGING_MINIO_SECRET_KEY}
      MINIO_CACHE: "on"
      MINIO_CACHE_DRIVES: "/mnt/drive1,/mnt/drive2,/mnt/cache{1...3}"
      MINIO_CACHE_QUOTA: 80
      MINIO_CACHE_AFTER: 3
      MINIO_CACHE_WATERMARK_LOW: 70
      MINIO_CACHE_WATERMARK_HIGH: 90
    command: server /data

  messaging-minio-client:
    image: minio/mc
    container_name: messsaging_client
    networks:
      - messsaging
    # insure that the server container is running before building the client
    depends_on:
      - messaging-minio-server
    entrypoint: >
      /bin/sh -c "
      /usr/bin/mc config host add myminio http://minio-server:9000 ${MESSAGING_MINIO_ACCESS_KEY} ${MESSAGING_MINIO_SECRET_KEY};
      /usr/bin/mc mb myminio/messaging-bucket;
      echo 'my content' > testfile.txt;
      /usr/bin/mc cp myfile.txt myminio/messaging-bucket;
      exit 0;
      "
  messaging-redis:
    container_name: messsaging_cache
    image: 'redis:alpine'
    networks:
      - messsaging
    hostname: redis
    ports:
      - '${MESSAGING_REDIS_PORT}:6379'

  messaging-postgres:
    container_name: messsaging_persistence
    image: 'postgres:latest'
    ports:
      - "${MESSAGING_DB_PORT}:5432"
    volumes:
      - '${MESSAGING_DATA_PATH}:/data/postgres'
    environment:
      POSTGRES_USER: ${MESSAGING_DB_USER}
      POSTGRES_PASSWORD: ${MESSAGING_DB_PW}
      POSTGRES_DB: ${MESSAGING_DB_NAME}
    networks:
      - messsaging

  messaging-pgadmin:
    links:
      - messaging-postgres:postgres
    container_name: messaging_pgadmin
    image: dpage/pgadmin4
    ports:
      - "${MESSAGING_DB_ADMIN_PORT}:80"
    volumes:
      - /data/pgadmin:/root/.pgadmin
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: admin
    networks:
      - messsaging
networks:
  messsaging:
